name: teval_py310
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py310hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=27.1.0=py310hcf8288c_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd233ad5_2
  - pip:
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - airportsdata==20250909
      - aitutor-assessmentkit==0.1.8
      - alembic==1.16.4
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - anyio==4.11.0
      - apache-tvm-ffi==0.1.2
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - astor==0.8.1
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - babel==2.17.0
      - banal==1.0.6
      - beautifulsoup4==4.14.2
      - bert-score==0.3.13
      - blake3==1.0.8
      - bleach==6.3.0
      - cachetools==6.2.1
      - cbor2==5.7.1
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.2
      - clean-text==0.6.0
      - click==8.2.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - compressed-tensors==0.12.2
      - contourpy==1.3.2
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.2
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - dataset==1.6.2
      - datasets==4.0.0
      - defusedxml==0.7.1
      - deprecated==1.3.1
      - depyf==0.20.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - emoji==1.7.0
      - evaluate==0.4.6
      - fastapi==0.121.1
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.3.1
      - fastjsonschema==2.21.2
      - fastrlock==0.8.3
      - filelock==3.18.0
      - flashinfer-python==0.5.2
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozendict==2.4.7
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gguf==0.17.1
      - googleapis-common-protos==1.72.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.10
      - imbalanced-learn==0.14.0
      - importlib-metadata==8.0.0
      - interegular==0.3.3
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - jmespath==1.0.1
      - joblib==1.5.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.2.2
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - mistune==3.1.4
      - model-hosting-container-standards==0.1.9
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.19.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.9.2
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - num2words==0.5.14
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.2.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openai==2.8.1
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.13
      - outlines==0.1.11
      - outlines-core==0.2.11
      - overrides==7.7.0
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - partial-json-parser==0.2.1.1.post6
      - peft==0.17.0
      - pillow==11.3.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - protobuf==4.25.8
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-extra-types==2.10.6
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - ray==2.51.1
      - referencing==0.37.0
      - regex==2025.7.34
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.6
      - rpds-py==0.28.0
      - safetensors==0.5.3
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.44.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - sqlalchemy==1.4.54
      - stanza==1.11.0
      - starlette==0.49.3
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.2.1
      - torch==2.9.0
      - torch-c-dlpack-ext==0.1.2
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.5.0
      - trl==0.19.0
      - typer==0.20.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - vllm==0.11.2
      - watchfiles==1.1.1
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - xformers==0.0.33.post1
      - xgrammar==0.1.25
      - xxhash==3.5.0
      - yarl==1.20.1
